image: golang:latest

variables:
  GOFLAGS: "-mod=vendor"
  GO111MODULE: "on"

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build ./...

vendor:
  stage: test
  script:
    - go mod verify
    - go mod tidy
    - git diff --exit-code

# Disabled pending https://github.com/johanbrandhorst/certify/issues/26
#generate:
#  stage: test
#  script:
#    - apt-get update
#    - apt-get install -y protobuf-compiler
#    - go install ./vendor/github.com/golang/protobuf/protoc-gen-go ./vendor/github.com/matryer/moq
#    - go generate -x ./...
#    - git diff --exit-code

test:
  stage: test
  services:
    - docker:dind
  variables:
    # Necessary to get dockertest to use Docker-in-Docker
    DOCKER_HOST: "tcp://docker:2375"
  script:
    - go install ./vendor/github.com/onsi/ginkgo/ginkgo
    - ginkgo -v -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress --skipPackage=vendor --skipMeasurements
