required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/matryer/moq",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.9.6"

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.1.6"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  version = "1.3.2"
